### ISSUE TITLE
Can't get `make lint` to run successfully

### ISSUE THREAD

**Issue by jacobweinstock** [tinkerbell/hegel#192]
`make lint` fails to run successfully with the following errors. I have `Python 3.10.6` installed.
```bash
$ make lint                                    
mkdir -p out/linters
curl -sfL https://github.com/hadolint/hadolint/releases/download/v2.6.1/hadolint-Linux-x86_64 > out/linters/hadolint-v2.10.0-x86_64
chmod u+x out/linters/hadolint-v2.10.0-x86_64
mkdir -p out/linters
curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b out/linters v1.50.1
golangci/golangci-lint info checking GitHub for tag 'v1.50.1'
golangci/golangci-lint info found version: 1.50.1 for v1.50.1/linux/amd64
golangci/golangci-lint info installed out/linters/golangci-lint
mv out/linters/golangci-lint out/linters/golangci-lint-v1.50.1-x86_64
mkdir -p out/linters/yamllint-1.28.0/lib
curl -sSfL https://github.com/adrienverge/yamllint/archive/refs/tags/v1.28.0.tar.gz | tar -C out/linters -zxf -
cd out/linters/yamllint-1.28.0 && PYTHONPATH=lib python setup.py -q install --prefix . --install-lib lib
/usr/lib/python3/dist-packages/setuptools/command/install.py:34: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/lib/python3/dist-packages/setuptools/command/easy_install.py:158: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  warnings.warn(
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 0.1.43ubuntu1 is an invalid version and will not be supported in a future release
  warnings.warn(
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning: 1.1build1 is an invalid version and will not be supported in a future release
  warnings.warn(
zip_safe flag not set; analyzing archive contents...
yamllint.__pycache__.config.cpython-310: module references __file__
/usr/lib/python3/dist-packages/pkg_resources/__init__.py:116: PkgResourcesDeprecationWarning:  is an invalid version and will not be supported in a future release
  warnings.warn(
out/linters/golangci-lint-v1.50.1-x86_64 run
WARN [runner] The linter 'structcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused. 
WARN [runner] The linter 'deadcode' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused. 
WARN [runner] The linter 'varcheck' is deprecated (since v1.49.0) due to: The owner seems to have abandoned the linter.  Replaced by unused. 
WARN [runner] The linter 'ifshort' is deprecated (since v1.48.0) due to: The repository of the linter has been deprecated by the owner.  
WARN [linters_context] rowserrcheck is disabled because of generics. You can track the evolution of the generics support by following the https://github.com/golangci/golangci-lint/issues/2649. 
WARN [linters_context] sqlclosecheck is disabled because of generics. You can track the evolution of the generics support by following the https://github.com/golangci/golangci-lint/issues/2649. 
WARN [linters_context] structcheck is disabled because of generics. You can track the evolution of the generics support by following the https://github.com/golangci/golangci-lint/issues/2649. 
WARN [linters_context] wastedassign is disabled because of generics. You can track the evolution of the generics support by following the https://github.com/golangci/golangci-lint/issues/2649. 
out/linters/hadolint-v2.10.0-x86_64 --no-fail ./Dockerfile
./Dockerfile:9 DL3018 warning: Pin versions in apk add. Instead of `apk add <package>` use `apk add <package>=<version>`
./Dockerfile:9 DL3019 info: Use the `--no-cache` switch to avoid the need to use `--update` and remove `/var/cache/apk/*` when done installing packages
./Dockerfile:11 DL3059 info: Multiple consecutive `RUN` instructions. Consider consolidation.
PYTHONPATH=out/linters/yamllint-1.28.0/lib out/linters/yamllint-1.28.0/bin/yamllint .
Traceback (most recent call last):
  File "/home/tink/repos/tinkerbell/hegel/out/linters/yamllint-1.28.0/bin/yamllint", line 33, in <module>
    sys.exit(load_entry_point('yamllint==1.28.0', 'console_scripts', 'yamllint')())
  File "/home/tink/repos/tinkerbell/hegel/out/linters/yamllint-1.28.0/bin/yamllint", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 957, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 548, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: No package metadata was found for yamllint
make: *** [Makefile:79: lint] Error 1
```
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Operating System and version (e.g. Linux, Windows, MacOS):
* Linux, Ubuntu 22.04.1 LTS

* How are you running Tinkerbell? Using Vagrant & VirtualBox, Vagrant & Libvirt, on Packet using Terraform, or give details:

* Link to your project or a code example to reproduce issue:

**Comment by chrisdoherty4** [comment]
I think we might want to just 'patch' this to get it functional. Its meant to be based on the `lint-install` tool (which I naively thought automatically updated repos) but that feels a little clunky in itself currently.

We might consider brainstorming a more automated approach long term.
